# Generated by Django 2.1.3 on 2018-12-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=500)),
                ('vehicle_name', models.CharField(max_length=500)),
                ('vehicle_access_token', models.CharField(max_length=500)),
                ('vehicle_refresh_token', models.CharField(max_length=500)),
                ('vehicle_location_latitude', models.CharField(max_length=500)),
                ('vehicle_location_longitude', models.CharField(max_length=500)),
                ('vehicle_destination_latitude', models.CharField(max_length=500)),
                ('vehicle_destination_longitude', models.CharField(max_length=500)),
            ],
        ),
    ]
