# Generated by Django 2.1.3 on 2018-12-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janus_backend_app', '0002_auto_20181201_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_mine',
            field=models.BooleanField(default=False),
        ),
    ]
