# Generated by Django 2.1.3 on 2018-12-02 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janus_backend_app', '0003_vehicle_is_mine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('location_type', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='is_mine',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_access_token',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_refresh_token',
        ),
    ]
