# Generated by Django 2.1.3 on 2018-12-02 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('janus_backend_app', '0004_auto_20181202_0036'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
